# Generated by Django 5.0 on 2024-01-02 16:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('branch_id', models.AutoField(primary_key=True, serialize=False)),
                ('branch_code', models.CharField(max_length=60)),
                ('branch_name', models.CharField(max_length=110)),
                ('branch_location', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Compartment',
            fields=[
                ('compartment_id', models.AutoField(primary_key=True, serialize=False)),
                ('compartment_name', models.CharField(max_length=90)),
                ('compartment_location', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('doc_id', models.AutoField(primary_key=True, serialize=False)),
                ('doc_classification_type', models.CharField(choices=[('Normal', 'Normal'), ('Classified', 'Classified')], default='Normal', max_length=90)),
                ('doc_type', models.CharField(choices=[('Vouchers', 'Vouchers'), ('Cheques', 'Cheques'), ('Client File', 'Client File'), ('Demand Draft', 'Demand Draft'), ('Guarantee', 'Guarantee'), ('Contracts', 'Contracts')], default='Vouchers', max_length=90)),
                ('doc_details', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('pkg_id', models.AutoField(primary_key=True, serialize=False)),
                ('pkg_name', models.CharField(max_length=100)),
                ('details', models.TextField()),
                ('packaging_size', models.CharField(choices=[('Box size 1', 'Box size 1'), ('Box size 2', 'Box size 2'), ('Plastic Bag', 'Plastic Bag')], default='Box size 1', max_length=90)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=90)),
                ('destruction_eligible_time', models.CharField(choices=[('1 Year', '1 Year'), ('2 Years', '2 Years'), ('3 Years', '3 Years'), ('4 Years', '4 Years'), ('5 Years', '5 Years'), ('6 Years', '6 Years'), ('7 Years', '7 Years'), ('8 Years', '8 Years')], default='1 Year', max_length=90)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Package.document')),
            ],
        ),
        migrations.CreateModel(
            name='PackageVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification_remarks', models.TextField()),
                ('verification_date', models.DateTimeField(auto_now_add=True)),
                ('authorizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('package_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Package.package')),
            ],
        ),
        migrations.CreateModel(
            name='Rack',
            fields=[
                ('rack_id', models.AutoField(primary_key=True, serialize=False)),
                ('rack_name', models.CharField(max_length=90)),
                ('compartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Package.compartment')),
            ],
        ),
        migrations.CreateModel(
            name='StoreRoom',
            fields=[
                ('store_room_id', models.AutoField(primary_key=True, serialize=False)),
                ('store_room_name', models.CharField(max_length=90)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Package.branch')),
                ('rack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Package.rack')),
            ],
        ),
        migrations.AddField(
            model_name='package',
            name='store_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Package.storeroom'),
        ),
    ]
