# Generated by Django 4.2.9 on 2024-04-08 04:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('branch_id', models.AutoField(primary_key=True, serialize=False)),
                ('branch_code', models.CharField(max_length=60)),
                ('branch_name', models.CharField(max_length=110)),
                ('branch_location', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('doc_id', models.AutoField(primary_key=True, serialize=False)),
                ('document', models.CharField(choices=[('Vouchers', 'Vouchers'), ('Cheques', 'Cheques'), ('Client File', 'Client File'), ('Demand Draft', 'Demand Draft'), ('Guarantee', 'Guarantee'), ('Contracts', 'Contracts')], default='Vouchers', max_length=90)),
                ('doc_type', models.CharField(choices=[('Normal', 'Normal'), ('Classified', 'Classified')], default='Normal', max_length=90)),
                ('doc_details', models.TextField(blank=True, null=True)),
                ('file_no', models.CharField(blank=True, max_length=90, null=True)),
                ('voucher_no', models.CharField(blank=True, max_length=90, null=True)),
                ('user_for_deposit', models.CharField(blank=True, max_length=90, null=True)),
                ('date_for_deposit', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('pkg_id', models.AutoField(primary_key=True, serialize=False)),
                ('pkg_name', models.CharField(max_length=100)),
                ('details', models.TextField()),
                ('packaging_size', models.CharField(choices=[('Box size 1', 'Box size 1'), ('Box size 2', 'Box size 2'), ('Plastic Bag', 'Plastic Bag')], default='Box size 1', max_length=90)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=90)),
                ('destruction_eligible_time', models.CharField(choices=[('1 Year', '1 Year'), ('2 Years', '2 Years'), ('3 Years', '3 Years'), ('4 Years', '4 Years'), ('5 Years', '5 Years'), ('6 Years', '6 Years'), ('7 Years', '7 Years'), ('8 Years', '8 Years')], default='1 Year', max_length=90)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('condition', models.CharField(choices=[('Good', 'Good'), ('Damaged (Mouse)', 'Damaged (Mouse)'), ('Damaged (Fire)', 'Damaged (Fire)'), ('Damaged (Accident)', 'Damaged (Accident)')], default='Good', max_length=50)),
                ('is_sealed', models.BooleanField(default=False)),
                ('is_collected', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='packages', to=settings.AUTH_USER_MODEL)),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Package.document')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Rack',
            fields=[
                ('rack_id', models.AutoField(primary_key=True, serialize=False)),
                ('rack_name', models.CharField(max_length=90)),
            ],
        ),
        migrations.CreateModel(
            name='StoreRoom',
            fields=[
                ('store_room_id', models.AutoField(primary_key=True, serialize=False)),
                ('store_room_name', models.CharField(max_length=90)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Package.branch')),
                ('rack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Package.rack')),
            ],
        ),
        migrations.CreateModel(
            name='PackageVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('verification_remarks', models.TextField()),
                ('verification_date', models.DateTimeField(auto_now_add=True)),
                ('authorizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='Package.package')),
            ],
            options={
                'ordering': ['-verification_date'],
            },
        ),
        migrations.CreateModel(
            name='Compartment',
            fields=[
                ('compartment_id', models.AutoField(primary_key=True, serialize=False)),
                ('compartment_name', models.CharField(max_length=90)),
                ('compartment_location', models.CharField(max_length=150)),
                ('rack', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compartments', to='Package.rack')),
            ],
        ),
    ]
