version: '3.11'

services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    environment:
      - DJANGO_SETTINGS_MODULE=DocumentManagementSystem.settings
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      - ENVIROMENT="development"
      - DMS_USER="default"
      - DMS_HOST="ep-white-hall-a4df3f04-pooler.us-east-1.aws.neon.tech"
      - DMS_PASSWORD="jlqoNB10brMnasd"
      - DMS_DATABASE="verceldb"
      - DMS_PORT="5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
