version: '3'

services:
  # Postgres database
  db:
    image: postgres:alpine3.18
    container_name: postgres_db
    env_file:
      - .env.dev
    restart: always
    ports:
      - 5432:5432

  # Django app
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: dms_app
    env_file:
      - .env.dev
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db

  # Redis container
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - 6379:6379
  
  # celery
  celery:
    restart: always
    build: 
      context: .
    command: celery -A DocumentManagementSystem worker -l info
    volumes:
      - .:/code
    container_name: celery
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - redis
      - app

  # Celery beat
  beat:
    build: 
      context: .
    command: celery -A DocumentManagementSystem beat -l info
    volumes:
      - .:/code
    container_name: beat
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - redis
      - app
