# Generated by Django 4.2.9 on 2024-04-08 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Package', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DestructionEligible',
            fields=[
                ('destruction_eligible_id', models.AutoField(primary_key=True, serialize=False)),
                ('is_expired', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('destruction_time', models.IntegerField(blank=True, null=True)),
                ('related_package', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='destruction_eligibility', to='Package.package')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
