# Generated by Django 4.2.9 on 2024-04-08 04:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Package', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreMonitoring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateField()),
                ('comments', models.TextField(blank=True, null=True)),
                ('store_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Package.storeroom')),
            ],
        ),
        migrations.CreateModel(
            name='DamagedPackageReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_date', models.DateField(auto_now_add=True)),
                ('damage_comments', models.TextField()),
                ('is_resolved', models.BooleanField(default=False)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Package.package')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
