# Generated by Django 4.2.9 on 2024-04-08 04:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Package', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageCollection',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('collection_date', models.DateTimeField(auto_now_add=True)),
                ('tampering_verification_remarks', models.TextField()),
                ('tampering_detected', models.BooleanField(blank=True, default=False, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('collector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Package.package')),
                ('store_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Package.storeroom')),
            ],
            options={
                'verbose_name': 'Package Collection',
                'verbose_name_plural': 'Package Collection',
                'ordering': ['package'],
            },
        ),
    ]
