# Generated by Django 4.2.9 on 2024-04-08 04:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Package', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_type', models.CharField(choices=[('photocopy', 'Provide Photocopy'), ('original', 'Provide Original Copy')], max_length=10)),
                ('reseal_package', models.BooleanField(default=False)),
                ('return_status', models.CharField(choices=[('not_returned', 'Not Returned'), ('returned', 'Returned')], default='not_returned', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remarks', models.TextField(help_text='Remarks (mandatory)')),
                ('authorization_remarks', models.TextField(help_text='Authorization Remarks (mandatory)')),
                ('access_type', models.CharField(choices=[('copy', 'Request for Copy'), ('original', 'Request for Original Copy')], max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('authorizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorized_requests', to=settings.AUTH_USER_MODEL)),
                ('package', models.ForeignKey(help_text='Package (mandatory)', on_delete=django.db.models.deletion.CASCADE, related_name='document_requests', to='Package.package')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_date', models.DateTimeField(auto_now_add=True)),
                ('return_date', models.DateTimeField(blank=True, null=True)),
                ('return_condition', models.TextField(blank=True, null=True)),
                ('access_provided_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('document_access', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='DocumentApps.documentaccess')),
            ],
        ),
        migrations.AddField(
            model_name='documentaccess',
            name='document_request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='access', to='DocumentApps.documentrequest'),
        ),
    ]
